# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    ports:
      - 8000:8000
    environment:
      - COMET_API_KEY = ${COMET_API_KEY}
#      args:
#        ARG: <ARG>
#    image: ift6758/serving:<TAG>
#    ports:
#      - <SERVING_PORT>:<SERVING_PORT>
#    environment:
#      DOCKER_ENV_VAR = ${LOCAL_ENV_VAR}
###### Uncomment below when you're ready to add the final notebook container to your docker compose
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    ports:
      - 8001:8001
##      args:
##        ARG: <ARG>
##    image: ift6758/streamlit:<TAG>
      # ports:
      #   - <STREAMLIT_PORT>:8001 #Replace <STREAMLIT_PORT> with the desired external port
##    environment:
##      OTHER_DOCKER_ENV_VAR = ${OTHER_LOCAL_ENV_VAR}
      

     
